# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Forex Explorer Continuous Integration and Continuous deployment (CI/CD) workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    tag-version: ${{ steps.version-tag.outputs.tag-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Calculate the version tag
        id: version-tag
        run: |
          export TZ="America/New_York"
          CURRENT_DATE_TIME="forexexplorer-$(date +'%Y.%m.%d-%I.%M.%S%p')"
          COMMIT_NUMBER=${{ github.run_number }}
          VERSION_TAG="${CURRENT_DATE_TIME}-${COMMIT_NUMBER}"
          echo "::set-output name=tag-version::${VERSION_TAG}"
          echo "version=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: surarohith/forex-explorer
          tags:
            ${{ steps.version-tag.outputs.version }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull the image from Docker Hub
        run: docker pull surarohith/forex-explorer:${{ needs.build.outputs.tag-version }}
      - name: Delete old container
        run: docker rm -f forex-explorer-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name forex-explorer-container surarohith/forex-explorer